# @package _global_.train.params

network:
  name: actor_critic
  separate: False
  space:
    continuous:
      mu_activation: None
      sigma_activation: None

      mu_init:
        name: default
      sigma_init:
        name: const_initializer
        val: 0
      fixed_sigma: True
  mlp:
    units: [256, 128, 64]
    activation: elu
    d2rl: False
    
    initializer:
      name: default
    regularizer:
      name: None
