include_self_modeling: false
policy:
  loss_weight: 0
policy_forward_kinematics:
  loss_weight: 0
num_serial_chains:
  loss_weight: 0
degree_count:
  loss_weight: 0
parent_count:
  loss_weight: 0
child_count:
  loss_weight: 0
parent_child_pose:
  loss_weight: 0
serial_chain_length:
  loss_weight: 0
parent_link_id:
  loss_weight: 0
